STORE_PROCESSED_NEWTYPE = {}
STORE_PROCESSED_TYPEVAR = {}
STORE_PROCESSED_GENERIC = {}
STORE_PROCESSED_ENUM = {}
STORE_PROCESSED_MISSING = {}
STORE_GENERIC_INTERFACE = {}  # 存储泛型实例，用于参数替换

TEMP_CONTEXT = {
    "typevar": {},
}  # 临时存储，用于参数替换
